test-warnings: false
strictness: medium
max-line-length: 120
uses:
  - django
  - celery
  - flask
autodetect: true
requirements:
  - requirements.txt
ignore-paths:
  - minghu6/gui
ignore-patterns:
  - ^minghu6_.*\.py$
python-targets:
  - 3