language: python
python:
- '3.4'
- '3.5'
- '3.6'
install:
- pip3 install ordered-set-minghu6
- python3 setup.py install
script: nosetests -w minghu6_test
sudo: false
notifications:
  on_success: change
  on_failure: always
  on_start: never
deploy:
  provider: pypi
  user: minghu6
  password:
    secure: HjRhV/zSppbAckN/oF/R4ldfyPk9HgYNC4aMF0ekst7Qrtt+YhIMzIdj78VN33YPq1X/xR0oaSx9890DR21P8oZh5mFlju5kSVG9ZPGgaDQRTT/HvVpRCt6cjzdx6b4mAPqdX4yaRJLmMzmtIluRmOtyRsaMiLxZ3Sr9LH+GM59s+qsxLYNpUMooFZBfvGH0BVgvnHxclntR4Bw1PxBY7ytQmJKf4QNJqfeq0EA6SXOUJAuuYTiib7+d4sLSbIDUhSG9lnEkeP8IizE9d9Nl/Fr1XHCZSFuOpRtB/BXK1xUt+l970RXV7LQX00lXjZb+F/kPDb1JUYI5iFNlotagpyD7I4z+b9NZx3PrIfxr58OAeLP8j1Nz58/FmeItIaGh+VKELtjr80FUpehJeQBSuxU0BNeZBvGvJFGbY+m4P0BaoeiluN8sihvcQfW51Meug+gsx77bh9vvJsavS6H/nHdHz6muyD7vL87yo/98EMM4MgIsx/ZmOKiwuIZcx0zvZnQZ9PlCqjFukygBHKPDRNmZc77UMSUZgZGn4iRCYsfEICO2XhIbV3i8yRVTYPDxuQ0tRQ9rYgNK4FjfEKsOIcXgjQT0TkBzEk+gqi7FljJMeuN6LviG64nGQxG34ZVTR64uGn7Zn0gAeV9i/r7tLBgOeBqMTeKis8neWRdrh1s=
  on:
    tags: true
    repo: minghu6/minghu6_py
