language: python
python:
- '3.4'
- '3.5'
- '3.6'
install:
- pip3 install ordered-set-minghu6
- python3 setup.py install
script: nosetests -w minghu6_test
sudo: false
notifications:
  on_success: change
  on_failure: always
  on_start: never
deploy:
  provider: pypi
  user: minghu6
  password:
    secure: oJZj1YJsD0qBPsZY9bjnPgeE71teyObQ04lcvfJo8L0kZ1K/Gr5yJsd5A6l91BX5tODJ5w+CE1WcW5NmjKwReVld4YVUj7qGI2mckHm53NNY5dcAXBg9tQBSdi6IG5dj+lcjbBhX/dVmpY1Q/sKd0eYS1QiSaVX0T9IIOqKfsKAjDyK5Jm7vsStcwKUjfGP/FA1fodaVdPUMH+KT/3662rg1EN/YjxWEE6GLdzNXOLoF1u2APvDl4xV5Bro+xQEkNjYwxiBPwhC1+jlkC3P8+sskqy148lrRCrXDpa9qL8tIHIqc1PkTP+kEECyjczzkxh1ViuvC5nGWoXOaBLsee+M8lYaG0kar7RDGZEiFDC8MhKu2u8IwFUH1PpeRJ43DAIMJfMDoOcbZZoecZkoQo2wMoAsrOBt8F0x8/l7Z3qT2HaAelU/I9VietEXY0NwTmRG2HiRgBcsRWx4O+VbkNfSu7HONrwEr8bt25UsmdPOuHEQHnWHNetW6vdHqAfgDDSFwYQW34WCxwikagalo2GyurtqU1UQE72LOpvvVuIEepU43EgDKsiqLa43NWKE+Gfb+FDi+1y/PKRjmGqWbTFpag5Fv/bzlhzw1Lt98TzOIuPkztpQ1P5IAXJfRWIHKw29Vl+LkKLrJYVuxrW5E7GTRtr2x7ULUPsnLJmiTz6k=
  on:
    tags: true
    repo: minghu6/minghu6_py
