# https://travis-ci.org/minghu6/minghu6_py
language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - python3 setup.py install

script: nosetests -w minghu6_test
sudo: false
notifications:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

