# https://travis-ci.org/soimort/you-get
language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
script: tox
sudo: false
notifications:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
